Rename the app to terra-settings
Terralego/django-terra-settings pull request #1
Opened 2020-09-18 08:31 UTC by CFarcy

2020-09-18 09:33 UTC, submarcos requested changes

2020-09-18 09:33 UTC, submarcos commented on .travis.yml
> +    - flake8 terra_settings
```suggestion
    - flake8 terra_settings test_terra_settings
```

2020-09-18 09:33 UTC, submarcos commented on terra_settings/apps.py
>  class TerraUtilsConfig(AppConfig):
```suggestion
class TerraSettingsConfig(AppConfig):
```

2020-09-18 09:33 UTC, submarcos commented on terra_settings/__init__.py
> +default_app_config = 'terra_settings.apps.TerraUtilsConfig'
```suggestion
default_app_config = 'terra_settings.apps.TerraSettingsConfig'
```

2020-09-21 08:06 UTC, submarcos approved these changes

2020-09-21 08:08 UTC, submarcos commented
don't forget to : 
* activate travis build
* activate codecov
* activate readthedocs builds

2020-09-21 09:50 UTC, submarcos commented on README.md
> +[![Test Coverage](https://api.codeclimate.com/v1/badges/186dad418b5c5cdb9cf8/test_coverage)](https://codeclimate.com/github/Terralego/django-terra-settings/test_coverage)
le test coverage est assuré par codecov (deux lignes au dessus, pas pas codeclimate qui regarde juste la qualité)

2020-09-21 09:51 UTC, CFarcy commented on README.md
> +[![Test Coverage](https://api.codeclimate.com/v1/badges/186dad418b5c5cdb9cf8/test_coverage)](https://codeclimate.com/github/Terralego/django-terra-settings/test_coverage)
Ok, je supprime alors

2020-09-23 09:25 UTC, merged